export enum PERMISSIONS {
    PERSON_ADD_PREMIUM = "PERSON_ADD_PREMIUM",
    PERSON_EDIT_PREMIUM = "PERSON_EDIT_PREMIUM",
    PERSON_DELETE_PREMIUM = "PERSON_DELETE_PREMIUM",
    PERSON_GET_PREMIUM = "PERSON_GET_PREMIUM",
    
    USER_DELETE_PREMIUM = "USER_DELETE_PREMIUM",
    USER_GET_PREMIUM = "USER_GET_PREMIUM",
    USER_EDIT_PREMIUM = "USER_EDIT_PREMIUM",
    
    PERMISSION_GROUP_ADD_PREMIUM = "PERMISSION_GROUP_ADD_PREMIUM",
    PERMISSION_GROUP_USER_DELETE_PREMIUM = "PERMISSION_GROUP_USER_DELETE_PREMIUM",
    PERMISSION_GROUP_USER_ADD_PREMIUM = "PERMISSION_GROUP_USER_ADD_PREMIUM",
    PERMISSION_GROUP_USER_GET_PREMIUM = "PERMISSION_GROUP_USER_GET_PREMIUM",
    PERMISSION_GROUP_GET_PREMIUM = "PERMISSION_GROUP_GET_PREMIUM",
    PERMISSION_GROUP_EDIT_PREMIUM = "PERMISSION_GROUP_EDIT_PREMIUM",
    PERMISSION_GROUP_DELETE_PREMIUM = "PERMISSION_GROUP_DELETE_PREMIUM",
    
    GROUP_PERMISSION_GET_PREMIUM = "GROUP_PERMISSION_GET_PREMIUM",
    GROUP_PERMISSION_DELETE_PREMIUM = "GROUP_PERMISSION_DELETE_PREMIUM",
    
    ASSIGN_PREMIUM_PERMISSION_GROUP_PREMIUM = "ASSIGN_PREMIUM_PERMISSION_GROUP_PREMIUM",
    
    PERMISSION_GET_PREMIUM = "PERMISSION_GET_PREMIUM",
    PERMISSION_ADD_PREMIUM = "PERMISSION_ADD_PREMIUM",
    PERMISSION_EDIT_PREMIUM = "PERMISSION_EDIT_PREMIUM",
    PERMISSION_DELETE_PREMIUM = "PERMISSION_DELETE_PREMIUM",
    
    ADD_MOVIE_PREMIUM = "ADD_MOVIE_PREMIUM",
    GET_MOVIE_PREMIUM = "GET_MOVIE_PREMIUM",
    EDIT_MOVIE_PREMIUM = "EDIT_MOVIE_PREMIUM",
    DELETE_MOVIE_PREMIUM = "DELETE_MOVIE_PREMIUM",
}
